### ISSUE TITLE
Connection reset by peer exception

### ISSUE THREAD

**Issue by CambodianCoder** [deercreeklabs/tube#1]
Handle more gracefully. May be related to https://github.com/deercreeklabs/capsule/issues/1.
![image](https://user-images.githubusercontent.com/35553625/117098280-3cc9f700-ad2b-11eb-99fe-121d313c2756.png)

**Comment by CambodianCoder** [comment]
Tracked down to https://github.com/deercreeklabs/tube/blob/9ab3f1dbc829c842c9188d1e02323082d5aaf5e9/src/deercreeklabs/tube/server.clj#L211. Adding a `when ws` check on line 200, 203 and 205, to match line https://github.com/deercreeklabs/tube/blob/9ab3f1dbc829c842c9188d1e02323082d5aaf5e9/src/deercreeklabs/tube/server.clj#L213 might be helpful.

**Comment by chadharrington** [comment]
@CambodianCoder Thanks for tracking that down! Can you make a PR for it?

**Comment by CambodianCoder** [comment]
Yep, PR has been made at https://github.com/deercreeklabs/tube/pull/3
