### ISSUE TITLE
missing implementation of on-disconnect*?

### ISSUE THREAD

**Issue by CambodianCoder** [deercreeklabs/tube#2]
In the file connection.cljc, `on-disconnect*` is declared in https://github.com/deercreeklabs/tube/blob/9ab3f1dbc829c842c9188d1e02323082d5aaf5e9/src/deercreeklabs/tube/connection.cljc#L33, but has no implementation in this file like the other IProtocols. Is this intentionally left-out, or should this be implemented?

**Comment by chadharrington** [comment]
@CambodianCoder After doing a little searching of the codebase, I can see that `on-disconnect*` is neither implemented nor called. It's just some leftover code and should be deleted from the protocol. Can you do that in your PR in to handle issue #1 ?

**Comment by CambodianCoder** [comment]
Yep! Pull request to address both issues made at https://github.com/deercreeklabs/tube/pull/3, @chadharrington.
